# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RiderClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RiderClient
  pod 'GoogleMaps', '~> 2.6.0'
  pod 'PusherSwift', '~> 5.1.1'
  pod 'Alamofire', '~> 4.6.0'
  pod 'PushNotifications'
end
